/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Segismar Junior
 */
public class ListarMetas extends javax.swing.JPanel {

    /**
     * Creates new form ListarMetas
     */
    public ListarMetas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_Titulo = new javax.swing.JPanel();
        lblTituloPage = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        lblIconPage = new javax.swing.JLabel();
        separaMeta = new javax.swing.JSeparator();
        pn_Dados = new javax.swing.JPanel();
        scrollTabelaMetas = new javax.swing.JScrollPane();
        tabelaMetas = new javax.swing.JTable();
        cmbMes = new javax.swing.JComboBox();
        lblMes = new javax.swing.JLabel();
        cmbAno = new javax.swing.JComboBox();
        lblAno = new javax.swing.JLabel();
        btnMostrar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pn_Titulo.setBackground(new java.awt.Color(49, 76, 212));
        pn_Titulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloPage.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lblTituloPage.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloPage.setText("Metas");
        pn_Titulo.add(lblTituloPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 16, -1, -1));

        lblSubtitulo.setFont(new java.awt.Font("Segoe UI Light", 1, 26)); // NOI18N
        lblSubtitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblSubtitulo.setText("Suas metas");
        pn_Titulo.add(lblSubtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 53, -1, -1));

        lblIconPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imgs/home-icon.png"))); // NOI18N
        pn_Titulo.add(lblIconPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 11, -1, 36));

        add(pn_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 100));

        separaMeta.setForeground(new java.awt.Color(255, 255, 255));
        add(separaMeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 670, -1));

        pn_Dados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelaMetas.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        tabelaMetas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Roupa", "R$ 500", "R$ 1000"},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Categoria", "Gastei", "Meta"
            }
        ));
        tabelaMetas.setToolTipText("");
        scrollTabelaMetas.setViewportView(tabelaMetas);

        pn_Dados.add(scrollTabelaMetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 540, 90));

        cmbMes.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        cmbMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho ", "Julho ", "Agosto ", "Setembro", "Outubro", "Novembro", "Dezembro", " " }));
        pn_Dados.add(cmbMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        lblMes.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        lblMes.setText("Mês:");
        pn_Dados.add(lblMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, 30));

        cmbAno.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        cmbAno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        pn_Dados.add(cmbAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        lblAno.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        lblAno.setText("Ano:");
        pn_Dados.add(lblAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, 30));

        btnMostrar.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        btnMostrar.setText("Mostrar");
        pn_Dados.add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, -1, -1));

        add(pn_Dados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 670, 350));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrar;
    private javax.swing.JComboBox cmbAno;
    private javax.swing.JComboBox cmbMes;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblIconPage;
    private javax.swing.JLabel lblMes;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTituloPage;
    private javax.swing.JPanel pn_Dados;
    private javax.swing.JPanel pn_Titulo;
    private javax.swing.JScrollPane scrollTabelaMetas;
    private javax.swing.JSeparator separaMeta;
    private javax.swing.JTable tabelaMetas;
    // End of variables declaration//GEN-END:variables
}
