/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controller.LoginController;
import Controller.PrincipalController;
import Controller.TabelaMetas;
import java.awt.Font;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Segismar Junior
 */
public class TelaCadastroMetas extends javax.swing.JPanel {
    private PrincipalController principal;
    private TabelaMetas tabelaMetas;
    /**
     * Creates new form TelaCadastroMetas
     */
    public TelaCadastroMetas() {
        
        startComponents();
        
    }
    private void iniciaTabela(){
        this.tabelaMetas = new TabelaMetas();
        Tabela.getTableHeader().setFont(new Font("Sergoe UI", Font.BOLD, 15));
        Tabela.setRowHeight(25);        
        Tabela.getTableHeader().setDefaultRenderer(new HeaderColor());
        Tabela.setModel(this.tabelaMetas);
    }
     
    private void startComponents(){
        initComponents();
        
        this.principal = new PrincipalController();
        carregaCategorias();
        iniciaTabela();
        txtValor.setDocument(new TeclasPermitidasDouble());
        
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_Background = new javax.swing.JPanel();
        pnTitulo = new javax.swing.JPanel();
        lblTituloPage = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        lblIconPage = new javax.swing.JLabel();
        separaMeta = new javax.swing.JSeparator();
        pn_DadosMetas = new javax.swing.JPanel();
        lblValor = new javax.swing.JLabel();
        smLimite = new javax.swing.JSlider();
        lblCategoria = new javax.swing.JLabel();
        lblPor_mes = new javax.swing.JLabel();
        lblMeses = new javax.swing.JLabel();
        lblNumMes = new javax.swing.JLabel();
        lblPretendoGastar = new javax.swing.JLabel();
        cmbCategoria = new javax.swing.JComboBox();
        btnCadastrar = new javax.swing.JButton();
        txtValor = new javax.swing.JTextField();
        scrollTabela = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        lblPretendoGastar1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        pn_Background.setBackground(new java.awt.Color(255, 255, 255));
        pn_Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnTitulo.setBackground(new java.awt.Color(49, 76, 212));

        lblTituloPage.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lblTituloPage.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloPage.setText("Cadastro de Metas");

        lblSubtitulo.setFont(new java.awt.Font("Segoe UI Light", 1, 26)); // NOI18N
        lblSubtitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblSubtitulo.setText("Metas");

        lblIconPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imgs/meta-icon.png"))); // NOI18N

        javax.swing.GroupLayout pnTituloLayout = new javax.swing.GroupLayout(pnTitulo);
        pnTitulo.setLayout(pnTituloLayout);
        pnTituloLayout.setHorizontalGroup(
            pnTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTituloLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubtitulo)
                    .addGroup(pnTituloLayout.createSequentialGroup()
                        .addComponent(lblIconPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTituloPage)))
                .addContainerGap(477, Short.MAX_VALUE))
        );
        pnTituloLayout.setVerticalGroup(
            pnTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblIconPage, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTituloPage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtitulo)
                .addContainerGap())
        );

        separaMeta.setForeground(new java.awt.Color(255, 255, 255));

        pn_DadosMetas.setBackground(new java.awt.Color(255, 255, 255));
        pn_DadosMetas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblValor.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        lblValor.setText("R$");
        pn_DadosMetas.add(lblValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 40));

        smLimite.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        smLimite.setMaximum(12);
        smLimite.setMinimum(1);
        smLimite.setToolTipText("");
        smLimite.setValue(1);
        smLimite.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                smLimiteStateChanged(evt);
            }
        });
        pn_DadosMetas.add(smLimite, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 150, 30));

        lblCategoria.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        lblCategoria.setText("Com:");
        pn_DadosMetas.add(lblCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        lblPor_mes.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        lblPor_mes.setText("Por:");
        pn_DadosMetas.add(lblPor_mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        lblMeses.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        lblMeses.setText("meses");
        pn_DadosMetas.add(lblMeses, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 50, -1));

        lblNumMes.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        lblNumMes.setText("1");
        pn_DadosMetas.add(lblNumMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 20, -1));

        lblPretendoGastar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        lblPretendoGastar.setForeground(new java.awt.Color(255, 102, 0));
        lblPretendoGastar.setText("Todas as Metas");
        pn_DadosMetas.add(lblPretendoGastar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));
        lblPretendoGastar.getAccessibleContext().setAccessibleName("Todas Metas");

        cmbCategoria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbCategoria.setToolTipText("");
        cmbCategoria.setBorder(null);
        cmbCategoria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbCategoriaFocusGained(evt);
            }
        });
        cmbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoriaActionPerformed(evt);
            }
        });
        pn_DadosMetas.add(cmbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 140, 30));

        btnCadastrar.setBackground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseClicked(evt);
            }
        });
        pn_DadosMetas.add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 110, 30));

        txtValor.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        txtValor.setForeground(new java.awt.Color(255, 102, 0));
        txtValor.setText("400,65");
        pn_DadosMetas.add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 150, 40));

        scrollTabela.setBackground(new java.awt.Color(255, 255, 255));

        Tabela.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Comida", "100.00", "12 meses"}
            },
            new String [] {
                "Meta", "Valor", "Período"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabela.setToolTipText("");
        Tabela.setFocusable(false);
        Tabela.setGridColor(new java.awt.Color(204, 255, 204));
        Tabela.setIntercellSpacing(new java.awt.Dimension(0, 0));
        Tabela.setRowHeight(25);
        Tabela.setSelectionBackground(new java.awt.Color(255, 102, 0));
        Tabela.setShowVerticalLines(false);
        Tabela.getTableHeader().setReorderingAllowed(false);
        scrollTabela.setViewportView(Tabela);

        pn_DadosMetas.add(scrollTabela, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 380, 190));

        lblPretendoGastar1.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        lblPretendoGastar1.setText("Pretendo gastar:");
        pn_DadosMetas.add(lblPretendoGastar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imgs/add3-icon.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.setName("lbl_addCat"); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        pn_DadosMetas.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 20, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_DadosMetas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(separaMeta, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(pn_Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separaMeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn_DadosMetas, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(pn_Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pn_DadosMetas.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void smLimiteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_smLimiteStateChanged
        lblNumMes.setText(String.valueOf(smLimite.getValue()));
    }//GEN-LAST:event_smLimiteStateChanged

    private void cmbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCategoriaActionPerformed

    private void btnCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseClicked
        double valor;    
        valor = Double.parseDouble(txtValor.getText().replace(',', '.'));
        
        String categoria = cmbCategoria.getSelectedItem().toString();
        int limite = smLimite.getValue();
               
        if(this.principal.encaminhaMeta(categoria, valor, limite)){
            JOptionPane.showMessageDialog(null, "Meta Cadastrada");
            iniciaTabela();
        }
        
    }//GEN-LAST:event_btnCadastrarMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        TelaCadastroCategoria tela = new TelaCadastroCategoria(false, true, this);
        tela.setRBganho();
        abreTela(tela);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void cmbCategoriaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbCategoriaFocusGained
        carregaCategorias();
    }//GEN-LAST:event_cmbCategoriaFocusGained

    public void carregaCategorias(){
        cmbCategoria.removeAllItems();
        principal.buscaCategorias("gasto").
            forEach(item -> cmbCategoria.addItem(item));
    }
    
    private void abreTela(Object o){
        JFrame tela = (JFrame) o;
        tela.setVisible(true);
        
        
    }   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabela;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JComboBox cmbCategoria;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblIconPage;
    private javax.swing.JLabel lblMeses;
    private javax.swing.JLabel lblNumMes;
    private javax.swing.JLabel lblPor_mes;
    private javax.swing.JLabel lblPretendoGastar;
    private javax.swing.JLabel lblPretendoGastar1;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTituloPage;
    private javax.swing.JLabel lblValor;
    private javax.swing.JPanel pnTitulo;
    private javax.swing.JPanel pn_Background;
    private javax.swing.JPanel pn_DadosMetas;
    private javax.swing.JScrollPane scrollTabela;
    private javax.swing.JSeparator separaMeta;
    private javax.swing.JSlider smLimite;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
