/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controller.LoginController;
import Controller.PrincipalController;
import java.awt.Color;
import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author Claudio
 */
public class TelaHome extends javax.swing.JPanel {
    private PrincipalController principal;

    /**
     * Creates new form telaHome
     */
    public TelaHome() {
        initComponents();
        this.principal = new PrincipalController();
        setInformacoesTelaHome();
    }
    
    public String obterNomeMes(int mes){ 
        String[] meses = {"Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"}; 
        return meses[mes]; 
    }
    public void setInformacoesTelaHome(){      
        Calendar data = Calendar.getInstance();
        String mes = obterNomeMes((data.get(Calendar.MONTH)));
        System.out.println(data.get(Calendar.YEAR));

        lblTituloPage.setText(lblTituloPage.getText() + LoginController.getUsuario().getNome() + "!");
        lblNome.setText(LoginController.getUsuario().getNome());        
        lblMes.setText(""+mes);
        double s = 0;
        lblSAnterior.setText(s+"");
        lblGanhos.setText("+"+principal.ganhosTotalHome()+"");
        lblGastos.setText(principal.gastosTotalHome()+"");
        lblSFinal.setText(principal.saldoTotalHome()+"");
        
        String saldoAnterior = lblSAnterior.getText();
        String ganho = lblGanhos.getText();
        String gasto = lblGastos.getText();
        String saldoFinal = lblSFinal.getText();
        
        
        /*
        lblSFinal.setText(this.principal.getSaldoFinalHome()+"");
        lblGanhos.setText(this.principal.getGanhosHome()+"");
        lblGastos.setText(this.principal.getGastosHome()+"");
        lblSAnterior.setText(this.principal.getSaldoIncial()+"");
        */
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTitulo = new javax.swing.JPanel();
        lblTituloPage = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        lblIconPage = new javax.swing.JLabel();
        lblDescrição = new javax.swing.JLabel();
        lblImgDescricao = new javax.swing.JLabel();
        separatorContent = new javax.swing.JSeparator();
        pnDados = new javax.swing.JPanel();
        lblTituloNome = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblTituloMes = new javax.swing.JLabel();
        lblMes = new javax.swing.JLabel();
        lblTituloSAnterior = new javax.swing.JLabel();
        lblSAnterior = new javax.swing.JLabel();
        lblTituloGastos = new javax.swing.JLabel();
        lblGastos = new javax.swing.JLabel();
        lblTituloGanhos = new javax.swing.JLabel();
        lblGanhos = new javax.swing.JLabel();
        lblTituloSFinal = new javax.swing.JLabel();
        lblSFinal = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(670, 450));
        setMinimumSize(new java.awt.Dimension(670, 450));
        setPreferredSize(new java.awt.Dimension(670, 450));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnTitulo.setBackground(new java.awt.Color(49, 76, 212));

        lblTituloPage.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lblTituloPage.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloPage.setText("Bem-Vindo, ");

        lblSubtitulo.setFont(new java.awt.Font("Segoe UI Light", 1, 26)); // NOI18N
        lblSubtitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblSubtitulo.setText("Informações do Usuário");

        lblIconPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imgs/home-icon.png"))); // NOI18N

        javax.swing.GroupLayout pnTituloLayout = new javax.swing.GroupLayout(pnTitulo);
        pnTitulo.setLayout(pnTituloLayout);
        pnTituloLayout.setHorizontalGroup(
            pnTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTituloLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubtitulo)
                    .addGroup(pnTituloLayout.createSequentialGroup()
                        .addComponent(lblIconPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTituloPage)))
                .addContainerGap(355, Short.MAX_VALUE))
        );
        pnTituloLayout.setVerticalGroup(
            pnTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblIconPage, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTituloPage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtitulo)
                .addContainerGap())
        );

        add(pnTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 100));

        lblDescrição.setBackground(new java.awt.Color(255, 255, 255));
        lblDescrição.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        lblDescrição.setText("Seus dados atuais");
        add(lblDescrição, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 170, 30));

        lblImgDescricao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImgDescricao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imgs/calendar-icon.png"))); // NOI18N
        add(lblImgDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 30, 30));

        separatorContent.setForeground(new java.awt.Color(207, 207, 207));
        add(separatorContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 630, 10));

        pnDados.setBackground(new java.awt.Color(255, 255, 255));
        pnDados.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnDados.setForeground(new java.awt.Color(204, 204, 204));
        pnDados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloNome.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        lblTituloNome.setText("Nome:");
        pnDados.add(lblTituloNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        lblNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNome.setText("*");
        pnDados.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 550, -1));

        lblTituloMes.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        lblTituloMes.setText("Mês Atual:");
        pnDados.add(lblTituloMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 100, -1));

        lblMes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMes.setText("*");
        pnDados.add(lblMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 110, -1));

        lblTituloSAnterior.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        lblTituloSAnterior.setText("Saldo Anterior:");
        pnDados.add(lblTituloSAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 130, -1));

        lblSAnterior.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSAnterior.setForeground(new java.awt.Color(153, 0, 153));
        lblSAnterior.setText("200,00");
        pnDados.add(lblSAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 120, -1));

        lblTituloGastos.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        lblTituloGastos.setText("Gastos:");
        pnDados.add(lblTituloGastos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 70, -1));

        lblGastos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGastos.setForeground(new java.awt.Color(255, 0, 0));
        lblGastos.setText("129,00");
        pnDados.add(lblGastos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 100, -1));

        lblTituloGanhos.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        lblTituloGanhos.setText("Ganhos:");
        pnDados.add(lblTituloGanhos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 70, -1));

        lblGanhos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGanhos.setForeground(new java.awt.Color(0, 153, 0));
        lblGanhos.setText("2340,00");
        pnDados.add(lblGanhos, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 90, -1));

        lblTituloSFinal.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        lblTituloSFinal.setText("Saldo Final:");
        pnDados.add(lblTituloSFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        lblSFinal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSFinal.setForeground(new java.awt.Color(0, 7, 255));
        lblSFinal.setText("2211,00");
        pnDados.add(lblSFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 90, -1));

        add(pnDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 630, 170));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDescrição;
    private javax.swing.JLabel lblGanhos;
    private javax.swing.JLabel lblGastos;
    private javax.swing.JLabel lblIconPage;
    private javax.swing.JLabel lblImgDescricao;
    private javax.swing.JLabel lblMes;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSAnterior;
    private javax.swing.JLabel lblSFinal;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTituloGanhos;
    private javax.swing.JLabel lblTituloGastos;
    private javax.swing.JLabel lblTituloMes;
    private javax.swing.JLabel lblTituloNome;
    private javax.swing.JLabel lblTituloPage;
    private javax.swing.JLabel lblTituloSAnterior;
    private javax.swing.JLabel lblTituloSFinal;
    private javax.swing.JPanel pnDados;
    private javax.swing.JPanel pnTitulo;
    private javax.swing.JSeparator separatorContent;
    // End of variables declaration//GEN-END:variables
}
