/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controller.PrincipalController;
import Controller.TabelaRelatorio;
import java.awt.Color;
import java.awt.Font;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Segismar Junior
 */
public class TelaRelatorio extends javax.swing.JPanel {
    private PrincipalController principal;
    private TabelaRelatorio tabelaRelatorio;

    /**
     * Creates new form TelaRelatorio
     */
    public TelaRelatorio() {
        initComponents();
        this.principal = new PrincipalController();
        this.tabelaRelatorio = new TabelaRelatorio();
        Calendar hoje = Calendar.getInstance();
        cmbMes.setSelectedIndex((hoje.get(Calendar.MONTH)));
        setInformacoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_Titulo = new javax.swing.JPanel();
        lblTituloPage = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        lblIconPage = new javax.swing.JLabel();
        separaMeta = new javax.swing.JSeparator();
        pn_Dados = new javax.swing.JPanel();
        cmbTipo = new javax.swing.JComboBox();
        lblTipo = new javax.swing.JLabel();
        cmbAno = new javax.swing.JComboBox();
        lblAno = new javax.swing.JLabel();
        cmbMes = new javax.swing.JComboBox();
        scrollTabela = new javax.swing.JScrollPane();
        TabelaMovimentacoes = new javax.swing.JTable();
        lblMes = new javax.swing.JLabel();
        btnMostrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pn_Titulo.setBackground(new java.awt.Color(49, 76, 212));
        pn_Titulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloPage.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lblTituloPage.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloPage.setText("Relatório");
        pn_Titulo.add(lblTituloPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 16, -1, -1));

        lblSubtitulo.setFont(new java.awt.Font("Segoe UI Light", 1, 26)); // NOI18N
        lblSubtitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblSubtitulo.setText("Suas movimentações");
        pn_Titulo.add(lblSubtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 53, -1, -1));

        lblIconPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imgs/relatorio-icon.png"))); // NOI18N
        pn_Titulo.add(lblIconPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 11, -1, 36));

        add(pn_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 100));

        separaMeta.setForeground(new java.awt.Color(255, 255, 255));
        add(separaMeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 670, -1));

        pn_Dados.setBackground(new java.awt.Color(255, 255, 255));
        pn_Dados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbTipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ambos", "Gastos", "Ganhos" }));
        pn_Dados.add(cmbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, -1, 30));

        lblTipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTipo.setText("Tipo:");
        pn_Dados.add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, 30));

        cmbAno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbAno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        pn_Dados.add(cmbAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, 30));

        lblAno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAno.setText("Ano:");
        pn_Dados.add(lblAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, 30));

        cmbMes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho ", "Julho ", "Agosto ", "Setembro", "Outubro", "Novembro", "Dezembro", " " }));
        pn_Dados.add(cmbMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, 30));

        TabelaMovimentacoes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TabelaMovimentacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Data", "Tipo", "Categoria", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaMovimentacoes.setToolTipText("");
        TabelaMovimentacoes.setFocusable(false);
        TabelaMovimentacoes.setGridColor(new java.awt.Color(204, 255, 204));
        TabelaMovimentacoes.setIntercellSpacing(new java.awt.Dimension(0, 0));
        TabelaMovimentacoes.setRowHeight(25);
        TabelaMovimentacoes.setSelectionBackground(new java.awt.Color(232, 57, 95));
        TabelaMovimentacoes.setShowVerticalLines(false);
        TabelaMovimentacoes.getTableHeader().setReorderingAllowed(false);
        scrollTabela.setViewportView(TabelaMovimentacoes);

        pn_Dados.add(scrollTabela, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 610, 160));

        lblMes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMes.setText("Mês:");
        pn_Dados.add(lblMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, 30));

        btnMostrar.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnMostrar.setText("Mostrar");
        btnMostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pn_Dados.add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));

        btnBuscar.setText("Buscar");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });
        pn_Dados.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, -1, -1));

        add(pn_Dados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 670, 340));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        Calendar data = Calendar.getInstance();
        int tipo = 0;
        int mes = cmbMes.getSelectedIndex()+1; 
        int tipoIndex = cmbTipo.getSelectedIndex();
        String mesNome = cmbMes.getSelectedItem().toString();
         
      
        
        int ano = Integer.parseInt(cmbAno.getSelectedItem().toString());
              
        //Ambos, Gastos, Ganhos
        switch(tipoIndex){
            case 0: tipo = 2; break;
            case 1: tipo = 0; break;
            case 2: tipo = 1; break;
        }       
               
        //this.tabelaRelatorio = this.principal.filtrarTabela(mes, ano, tipo);
        TabelaMovimentacoes.setModel(this.tabelaRelatorio);        
    }//GEN-LAST:event_btnBuscarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaMovimentacoes;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JComboBox cmbAno;
    private javax.swing.JComboBox cmbMes;
    private javax.swing.JComboBox cmbTipo;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblIconPage;
    private javax.swing.JLabel lblMes;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTituloPage;
    private javax.swing.JPanel pn_Dados;
    private javax.swing.JPanel pn_Titulo;
    private javax.swing.JScrollPane scrollTabela;
    private javax.swing.JSeparator separaMeta;
    // End of variables declaration//GEN-END:variables

    private void setInformacoes() {
        //this.tabelaRelatorio = this.principal.iniciaTabela();
        
        TabelaMovimentacoes.getTableHeader().setFont(new Font("Sergoe UI", Font.BOLD, 15));
        TabelaMovimentacoes.setRowHeight(25);        
        TabelaMovimentacoes.getTableHeader().setDefaultRenderer(new HeaderColor());
        
        TabelaMovimentacoes.setModel(this.tabelaRelatorio);
        
        
    }
}
