/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controller.PrincipalController;
import javax.swing.JOptionPane;

/**
 *
 * @author Lidia
 */
public class TelaCadastroFormadePagamento extends javax.swing.JFrame {

    private PrincipalController principal;
    private final Object telaAnterior;

    public TelaCadastroFormadePagamento(Object o) {
        initComponents();
        this.principal = new PrincipalController();
        this.telaAnterior = o;
        startComponentes();
    }

    public void startComponentes(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_Background = new javax.swing.JPanel();
        pnTitulo = new javax.swing.JPanel();
        lblTituloPage = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        lblIconPage = new javax.swing.JLabel();
        separatorContent = new javax.swing.JSeparator();
        pn_DadosCategoria = new javax.swing.JPanel();
        lblDescricao = new javax.swing.JLabel();
        btnLancar = new javax.swing.JButton();
        txtDescricao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pn_Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnTitulo.setBackground(new java.awt.Color(49, 76, 212));

        lblTituloPage.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lblTituloPage.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloPage.setText("Cadastro de Formas de Pagamentos");

        lblSubtitulo.setFont(new java.awt.Font("Segoe UI Light", 1, 26)); // NOI18N
        lblSubtitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblSubtitulo.setText("Forma de Pagamento");

        lblIconPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imgs/categoria-icon.png"))); // NOI18N

        javax.swing.GroupLayout pnTituloLayout = new javax.swing.GroupLayout(pnTitulo);
        pnTitulo.setLayout(pnTituloLayout);
        pnTituloLayout.setHorizontalGroup(
            pnTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTituloLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubtitulo)
                    .addGroup(pnTituloLayout.createSequentialGroup()
                        .addComponent(lblIconPage, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTituloPage)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        pnTituloLayout.setVerticalGroup(
            pnTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblIconPage, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTituloPage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtitulo)
                .addContainerGap())
        );

        pn_Background.add(pnTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 100));

        separatorContent.setForeground(new java.awt.Color(207, 207, 207));
        pn_Background.add(separatorContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 410, 10));

        pn_DadosCategoria.setBackground(new java.awt.Color(255, 255, 255));
        pn_DadosCategoria.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDescricao.setBackground(new java.awt.Color(255, 255, 255));
        lblDescricao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDescricao.setText("Descrição: ");
        pn_DadosCategoria.add(lblDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        btnLancar.setBackground(new java.awt.Color(255, 255, 255));
        btnLancar.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnLancar.setText("Lançar");
        btnLancar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLancar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLancarMouseClicked(evt);
            }
        });
        pn_DadosCategoria.add(btnLancar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

        txtDescricao.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        pn_DadosCategoria.add(txtDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 200, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imgs/formas2-icon.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(200, 65));
        jLabel1.setMinimumSize(new java.awt.Dimension(100, 112));
        pn_DadosCategoria.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 390, 100));

        pn_Background.add(pn_DadosCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 410, 220));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pn_Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLancarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLancarMouseClicked
        
        String descricao = txtDescricao.getText();

        if(this.principal.encaminhaCadastrodeFormadePagamento(descricao)){
            JOptionPane.showMessageDialog(null, "Forma de Pagamento cadastrada");
            this.dispose();
            carrega(this.telaAnterior);
        }
    }//GEN-LAST:event_btnLancarMouseClicked
    
    private void carrega(Object o){
        if(o instanceof TelaCadastroLancamento){
            TelaCadastroLancamento tela = (TelaCadastroLancamento) o;
            tela.carregaFormas();
            tela.validate();
        }       
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFormadePagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFormadePagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFormadePagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFormadePagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroFormadePagamento(this).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLancar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblIconPage;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTituloPage;
    private javax.swing.JPanel pnTitulo;
    private javax.swing.JPanel pn_Background;
    private javax.swing.JPanel pn_DadosCategoria;
    private javax.swing.JSeparator separatorContent;
    private javax.swing.JTextField txtDescricao;
    // End of variables declaration//GEN-END:variables
}
